language: ruby
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libnotify1
  - gem update --system
  - gem --version
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - ree
matrix:
  allow_failures:
    - rvm: 2.0.0
